# vars/mysql_replication_config.yml
---
# Number of slave containers (n)
num_slaves: 2

# Container names
master_container_name: mysql_master

# Docker MySQL image and credentials
mysql_image: mysql:5.7
mysql_root_password: "pass"
mysql_replication_user: repl_user
mysql_replication_password: "pass"

# SSL certificate settings
certs_path: "/tmp/mysql-certs"           # local folder to store generated certs
mysql_common_name: "mysql.local"

# Networking (adjust these to your needs)
master_host_ip: "127.0.0.1"                # or your Docker host IP
master_host_port: 3307                   # published port for master container

# List of ports for each slave container (must have num_slaves entries)
slave_ports:
  - 3308
  - 3309

# Port for a new slave if/when needed after failover
new_slave_port: 3310
